version: "3.9"

services:
  frontend:
    build:
      context: ./frontend/medops
    image: medops_frontend:latest
    ports:
      - "8080:80"
    env_file:
      - .env.production
    environment:
      - VITE_API_URL=http://localhost:8000/api/
      - VITE_DEV_TOKEN=${VITE_DEV_TOKEN}
    depends_on:
      - backend
    networks:
      - medops_net
    volumes:
      - ./frontend/medops/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media:ro

  backend:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 medops.wsgi:application
    ports:
      - "8000:8000"
    env_file:
      - .env.production
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_LOG_FILE=${DJANGO_LOG_FILE}
      - CORS_ALLOWED_ORIGINS=http://localhost:8080,http://127.0.0.1:8080
    depends_on:
      db:
        condition: service_started
      icdapi_es:
        condition: service_started
      icdapi_en:
        condition: service_started
    networks:
      - medops_net
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - ./data:/app/data

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      # CAMBIO CLAVE: Ahora los datos viven en la carpeta f√≠sica 'postgres_data'
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - medops_net

  icdapi_es:
    image: whoicd/icd-api
    container_name: icdapi_es
    ports:
      - "8081:80"
    environment:
      - acceptLicense=true
      - saveAnalytics=false
      - include=2025-01_es
    networks:
      - medops_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/icd/release/11/2025-01/mms"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s

  icdapi_en:
    image: whoicd/icd-api
    container_name: icdapi_en
    ports:
      - "8082:80"
    environment:
      - acceptLicense=true
      - saveAnalytics=false
      - include=2025-01_en
    networks:
      - medops_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/icd/release/11/2025-01/mms"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s

# El bloque de volumes se ha eliminado ya que usamos rutas relativas (./)

networks:
  medops_net:
    driver: bridge